
logging:
  level:
    org:
      hibernate:
        engine:
          internal:
            StatisticalLoggingSessionEventListener: WARN
    root: INFO

server:
  compression:
    enabled: true
  connection-timeout: 30000ms
  port: 8082
  servlet:
    context-path: /${spring.application.name}
spring:
  datasource:
    hikari:
      auto-commit: false
      connection-test-query: select getdate() as date
      connectivity-check-timeout-ms: 1000
      maximum-pool-size: 100
      minimum-idle: 40
      validation-timeout: 2000
    password: Aa111111
    url: jdbc:log4jdbc:sqlserver://localhost:1433;databaseName=facility_service
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: SA
  jpa:
    hibernate:
      ddl-auto: none
    mapping-resources:
      - META-INF/hibernate-mapping.xml
    properties:
      hibernate:
        connection:
          release_mode: auto
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        generate_statistics: true
        jdbc:
          use_scrollable_resultset: true
          use_streams_for_binary: true
        use_sql_comments: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
