spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
     #ddl-auto: update
    show-sql: true



